databases:
- name: mattermost
  plan: standard

services:
- type: pserv
  name: mattermost-minio
  env: docker
  dockerfilePath: ./minio/Dockerfile
  dockerContext: ./minio
  disk:
    name: data
    mountPath: /data
  envVars:
  - key: MINIO_ACCESS_KEY
    value: 9DG1XAAGFDOB39WK217V
  - key: MINIO_SECRET_KEY
    generateValue: true

- type: pserv
  name: mattermost-es
  env: docker
  plan: starter plus
  dockerfilePath: ./elastic/Dockerfile
  dockerContext: ./elastic
  disk:
    name: esdata
    mountPath: /usr/share/elasticsearch/data
  envVars:
  - key: ES_JAVA_OPTS
    value: "-Xms512m -Xmx512m"
  - key: discovery.type
    value: single-node

- type: web
  name: mattermost
  env: docker
  plan: starter plus
  dockerfilePath: ./app/Dockerfile
  dockerContext: ./app
  numInstances: 2
  envVars:
  - key: MM_USERNAME
    fromDatabase:
      name: mattermost
      property: user
  - key: MM_PASSWORD
    fromDatabase:
      name: mattermost
      property: password
  - key: MM_DBNAME
    fromDatabase:
      name: mattermost
      property: database
  - key: MM_SQLSETTINGS_DRIVERNAME
    value: postgres
  - key: DB_HOST
    fromDatabase:
      name: mattermost
      property: host
  - key: MM_SERVICESETTINGS_LISTENADDRESS
    value: ":10000"
  - key: MM_FILESETTINGS_DRIVERNAME
    value: amazons3
  - key: MM_FILESETTINGS_AMAZONS3BUCKET
    value: mattermost
  - key: MM_FILESETTINGS_AMAZONS3ACCESSKEYID
    value: 9DG1XAAGFDOB39WK217V
  - key: MM_FILESETTINGS_AMAZONS3SECRETACCESSKEY
    sync: false
  - key: MM_FILESETTINGS_AMAZONS3HOST
    fromService:
      type: pserv
      name: mattermost-minio
      property: host
  - key: MM_FILESETTINGS_AMAZONS3PORT
    fromService:
      type: pserv
      name: mattermost-minio
      property: port
  - key: MM_FILESETTINGS_AMAZONS3SSL
    value: "false"
  - key: MM_ELASTICSEARCHSETTINGS_ENABLEINDEXING
    value: "true"
  - key: MM_ELASTICSEARCHSETTINGS_ENABLESEARCHING
    value: "true"
  - key: MM_ELASTICSEARCHSETTINGS_USERNAME
    value: ""
  - key: MM_ELASTICSEARCHSETTINGS_PASSWORD
    value: ""
  - key: MM_ELASTICSEARCHSETTINGS_HOST
    fromService:
      type: pserv
      name: mattermost-es
      property: host
  - key: MM_ELASTICSEARCHSETTINGS_PORT
    fromService:
      type: pserv
      name: mattermost-es
      property: port
  - key: MM_CLUSTERSETTINGS_ENABLE
    value: "true"
  - key: MM_CLUSTERSETTINGS_CLUSTERNAME
    value: render
